language: scala
scala:
  - 2.12.7

install:
  sbt reload update

script:
  - sbt ++$TRAVIS_SCALA_VERSION test

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client