language: scala
scala:
  - 2.12.7

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE play_db;'
  
install:
  sbt reload update

script:
  - sbt 'testOnly *TestDatabase'
#  - sbt 'testOnly *Spec'